### ISSUE TITLE
Migrate Thermal Conductivity data

### ISSUE THREAD

**Issue by maneetgoyal** [manufac-analytics/perry#17]
- Table 2-147 needs to be migrated.
- Sample data is pushed for hints.

**Comment by maneetgoyal** [comment]
@sumitnegi7 Qurban (@qur786) shall be working on some of the data migration issues. Please brief him tomorrow after stand-up.

**Comment by sumitnegi7** [comment]
> @sumitnegi7 Qurban (@qur786) shall be working on some of the data migration issues. Please brief him tomorrow after stand-up.

Okay sir

**Comment by maneetgoyal** [comment]
@qur786 Anything pending here? Or can it be closed?

**Comment by qur786** [comment]
It can also be closed @maneetgoyal
