### ISSUE TITLE
Mirgate Vaport Thermal Conductivity

### ISSUE THREAD

**Issue by maneetgoyal** [manufac-analytics/perry#68]
- TABLE 2-145 Vapor Thermal Conductivity of Inorganic and Organic Substances [W/(m∙K)]

**Comment by qur786** [comment]
Sure sir 👍

**Comment by maneetgoyal** [comment]
@sumitnegi7 and @saikat-samanta Please split tasks accordingly. Try to get it ready by tomorrow. Qurban’s automation script might make it possible

**Comment by qur786** [comment]
Ok sure @maneetgoyal sir ,but there are some inconsistencies with data so their need to do some tinkering before running the script , so can I be the only one who migrates the data    and @sumitnegi7  and @saikat-samanta  will only review

**Comment by maneetgoyal** [comment]
Sounds good

**Comment by saikat-samanta** [comment]
@qur786, If you think, You need my help to migrate data. Please ping me.

**Comment by qur786** [comment]
> @qur786, If you think, You need my help to migrate data. Please ping me.

thank you for the help saikat , I have prepared the data , the tests are failing of batch 1 that's why this issue is taking so much time

**Comment by qur786** [comment]
done 👍
