### ISSUE TITLE
Add `ml-regression` sample

### ISSUE THREAD

**Issue by maneetgoyal** [manufac-analytics/perry#80]
Lib. to be used: 

1. https://github.com/mljs/regression
2. https://github.com/mljs/random-forest

- All the regression models available in the above 2 packages should be used for training
- All the models should be compared
- Hyper parameter optimization should be performed where applicable
- https://github.com/mljs/param-grid may be useful in hyper param optimization

**Comment by qur786** [comment]
Can we connect @maneetgoyal sir, on what implementation I have to make.

**Comment by maneetgoyal** [comment]
@qur786 Try to study this library in the meantime, will ping in sometime

**Comment by maneetgoyal** [comment]
Code should be added in `src/models/regression/index.ts`

**Comment by maneetgoyal** [comment]
https://hackernoon.com/machine-learning-with-javascript-part-1-9b97f3ed4fe5

**Comment by maneetgoyal** [comment]
Ref: https://people.duke.edu/~rnau/compare.htm

How to compare regression models' performance?

**Comment by maneetgoyal** [comment]
Sample data set to be used: 

1. https://archive.ics.uci.edu/ml/datasets/wine+quality

**Comment by maneetgoyal** [comment]
@qur786 Due to missing types, discard, `ml-regression`. Use the following instead:

- ml-regression-simple-linear
- ml-regression-exponential

**Comment by maneetgoyal** [comment]
>ml-regression-simple-linear, @maneetgoyal sir (Why this library, we can't use it for multi-independent variable)

@qur786 right, it can be removed

**Comment by qur786** [comment]
similar to the first one @maneetgoyal sir, `ml-regression-exponential` and `ml-regression-power` these two algorithm is similar to the `Simple Linear Regression Algorithm`.
![image](https://user-images.githubusercontent.com/79472606/148645667-35da5ace-db5e-4d4e-bd66-242435a5fc85.png)
![image](https://user-images.githubusercontent.com/79472606/148645701-7b624e5d-adf4-460f-a781-105dade1f859.png)

**Comment by maneetgoyal** [comment]
@qur786 The regression models deps are added via https://github.com/manufac-analytics/perry/commit/c937ff0ec50498a0e014d3fd60ffe792e6725a72.

will remove `ml-regression-exponential` shortly

**Comment by maneetgoyal** [comment]
ml-param-grid didn't have types so https://www.npmjs.com/package/kombi is installed instead. The functionality seems exact

**Comment by qur786** [comment]
@maneetgoyal sir, changing data from `csv` to `json` was a good idea , but most of the dataset that are available for machine learning are of type csv.

**Comment by qur786** [comment]
@maneetgoyal sir can we use this package from `mljs` for matrix manipulation if needed?

**Comment by qur786** [comment]
@maneetgoyal sir , I think this `ml-regression-robust-polynomial` also similar to `ml-regression-robust-polynomial`. So I think we shouldn't be working with this as well.

**Comment by maneetgoyal** [comment]
> @maneetgoyal sir, changing data from `csv` to `json` was a good idea , but most of the dataset that are available for machine learning are of type csv.

don't worry about, the task in this issue is to do sample modeling; ignore file handiling for now

**Comment by maneetgoyal** [comment]
> @maneetgoyal sir can we use this package from `mljs` for matrix manipulation if needed?

question unclear

**Comment by maneetgoyal** [comment]
> @maneetgoyal sir , I think this `ml-regression-robust-polynomial` also similar to `ml-regression-robust-polynomial`. So I think we shouldn't be working with this as well.

question unclear

**Comment by qur786** [comment]
> > @maneetgoyal sir can we use this package from `mljs` for matrix manipulation if needed?
> 
> question unclear

Sorry @maneetgoyal sir, I actually didn't attach the link of the  package `ml-matrix` https://github.com/mljs/matrix , this is a dependency of `RandomForest` Package as well. So that we can use it to compare, add substract large `matrices` and this kind of works.

**Comment by qur786** [comment]
> > @maneetgoyal sir , I think this `ml-regression-robust-polynomial` also similar to `ml-regression-robust-polynomial`. So I think we shouldn't be working with this as well.
> 
> question unclear

@maneetgoyal sir  as `ml-regression-robust-polynomial` , the `ml-regression-robust-polynomial` package also deals with only `one independent variable`. just like Simple Linear Regression. Should we use it ?

**Comment by maneetgoyal** [comment]
> > > @maneetgoyal sir can we use this package from `mljs` for matrix manipulation if needed?
> > 
> > 
> > question unclear
> 
> Sorry @maneetgoyal sir, I actually didn't attach the link of the package `ml-matrix` https://github.com/mljs/matrix , this is a dependency of `RandomForest` Package as well. So that we can use it to compare, add substract large `matrices` and this kind of works.

yeah it can be use if there is a need

**Comment by maneetgoyal** [comment]
> @maneetgoyal sir as `ml-regression-robust-polynomial` , the `ml-regression-robust-polynomial` package also deals with only `one independent variable`. just like Simple Linear Regression. Should we use it ?

yeah can be skipped

**Comment by maneetgoyal** [comment]
Fixed via #82
